routing.api:
    resource: 'Resources/routing/routing__api.yml'
    prefix: /api/

login:
    path: /login
    controller: App\Controller\DefaultController::index

logout:
    path: /logout

index:
    path: /
    controller: App\Controller\DefaultController::index

index.all:
    path: /{path}
    defaults: { _controller: App\Controller\DefaultController::index, path: '' }
    requirements:
        path: .*
