<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHS2kwY1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHS2kwY1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHS2kwY1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHS2kwY1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHS2kwY1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HS2kwY1',
    'container.build_id' => '0b2c1270',
    'container.build_time' => 1560182736,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHS2kwY1');
